name: project

on: ["push", "workflow_dispatch"]

jobs:
  build-app:
    name: Build App
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode 13.2.1
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Dependencies fetch
        run: |
           tuist fetch
      - name: Generate project
        run: |
          tuist generate
      - name: Build App
        run: |
          make build-app
  test-App:
    name: Test App
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode 13.2.1
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Dependencies fetch
        run: |
           tuist dependencies fetch
      - name: Generate project
        run: |
          tuist generate
      - name: Test App
        run: |
          make test-app
      
